on:
  push:
    branches:
    - main
    - dev_mooooonkrui
  workflow_dispatch:

jobs:
  test:
    name: Auto test using nu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install pkg-config libssl-dev build-essential && npm install -g nushell
    - name: Make
      run: mkdir build && make clean && make
    - name: Test
      run: nu auto_test.nu
