on:
  push:
    branches:
    - main
    - dev_mooooonkrui
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    name: Auto test using nu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install pkg-config libssl-dev build-essential && make depend
    - name: Make
      run: mkdir build && make clean && make MODE=DEBUG
    - name: Test
      run: touch test_result.json && make test_all
    - name: Show
      run: cat test_result.json